services:
  qwizzlearn:
    build:
      context: .
    ports:
      - "8001:8000" # Map host port 8001 to container port 8000
    container_name: qwizzlearn
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:8000/health').getcode()",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

    depends_on:
      - db
    volumes:
      - .:/app # Mount current directory to /app in the container

  db:
    image: postgres:15.6
    container_name: qwizzlearn-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USER}"]
      interval: 10s
      retries: 3
      timeout: 5s
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
  # redis:
  #   image: redis:alpine
  #   restart: always
  #   hostname: "redis"
  #   ports:
  #     - "6329:6379"
  #   volumes:
  #     - redis_data:/data
  #   command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 3

networks:
  default:
    driver: bridge

volumes:
  postgres_data:
  # redis_data:
