"""add updated_at column to difficulty model

Revision ID: 1515a42c96bf
Revises: 84c9955d4ba0
Create Date: 2024-09-08 16:35:24.924338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1515a42c96bf'
down_revision: Union[str, None] = '84c9955d4ba0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('difficulties', sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('difficulties', 'updated_at')
    # ### end Alembic commands ###
