"""Token, Device, and Session models

Revision ID: 1f8ff8a0e09f
Revises: 673e02ff8751
Create Date: 2025-01-26 17:08:26.719195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1f8ff8a0e09f'
down_revision: Union[str, None] = '673e02ff8751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
