"""add assigned_by field to role permissions

Revision ID: 46a2b372ef4e
Revises: 1287b2c2394d
Create Date: 2024-09-12 06:14:24.446187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '46a2b372ef4e'
down_revision: Union[str, None] = '1287b2c2394d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_permissions', sa.Column('assigned_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'role_permissions', 'users', ['assigned_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.drop_column('role_permissions', 'assigned_by')
    # ### end Alembic commands ###
