"""update db fields

Revision ID: 7fc05033e89f
Revises: 89521cc4bf4b
Create Date: 2024-09-14 17:48:28.121447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7fc05033e89f'
down_revision: Union[str, None] = '89521cc4bf4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question_time_tracking', 'quiz_attempt_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('question_time_tracking', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'question_time_tracking', 'questions', ['question_id'], ['id'])
    op.create_foreign_key(None, 'question_time_tracking', 'quiz_attempts', ['quiz_attempt_id'], ['id'])
    op.create_foreign_key(None, 'questions', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'questions', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'questions', 'difficulties', ['difficulty_id'], ['id'])
    op.create_foreign_key(None, 'quiz_attempts', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'quiz_attempts', 'quizzes', ['quiz_id'], ['id'])
    op.create_foreign_key(None, 'quiz_feedback', 'quizzes', ['quiz_id'], ['id'])
    op.create_foreign_key(None, 'quiz_progress', 'quiz_attempts', ['quiz_attempt_id'], ['id'])
    op.create_foreign_key(None, 'quiz_progress', 'questions', ['question_id'], ['id'])
    op.create_foreign_key(None, 'quiz_reports', 'quizzes', ['quiz_id'], ['id'])
    op.alter_column('quiz_schedule', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'quiz_schedule', 'quizzes', ['quiz_id'], ['id'])
    op.create_foreign_key(None, 'quiz_settings', 'quizzes', ['quiz_id'], ['id'])
    op.create_foreign_key(None, 'quizzes', 'difficulties', ['difficulty'], ['id'])
    op.create_foreign_key(None, 'quizzes', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'tags', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.drop_constraint(None, 'quiz_settings', type_='foreignkey')
    op.drop_constraint(None, 'quiz_schedule', type_='foreignkey')
    op.alter_column('quiz_schedule', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'quiz_reports', type_='foreignkey')
    op.drop_constraint(None, 'quiz_progress', type_='foreignkey')
    op.drop_constraint(None, 'quiz_progress', type_='foreignkey')
    op.drop_constraint(None, 'quiz_feedback', type_='foreignkey')
    op.drop_constraint(None, 'quiz_attempts', type_='foreignkey')
    op.drop_constraint(None, 'quiz_attempts', type_='foreignkey')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'question_time_tracking', type_='foreignkey')
    op.drop_constraint(None, 'question_time_tracking', type_='foreignkey')
    op.alter_column('question_time_tracking', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('question_time_tracking', 'quiz_attempt_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
