"""add unique constraint to quiz attempts

Revision ID: 9a229b525159
Revises: 544d50479a07
Create Date: 2024-09-15 14:00:35.035593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9a229b525159'
down_revision: Union[str, None] = '544d50479a07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz_attempts', 'quiz_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('quiz_attempts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint('uq_quiz_attempt_user_quiz', 'quiz_attempts', ['user_id', 'quiz_id', 'attempt_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_quiz_attempt_user_quiz', 'quiz_attempts', type_='unique')
    op.alter_column('quiz_attempts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('quiz_attempts', 'quiz_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
