"""remove name from permissions

Revision ID: 1287b2c2394d
Revises: ec2dfe32dd90
Create Date: 2024-09-12 01:03:23.486818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1287b2c2394d'
down_revision: Union[str, None] = 'ec2dfe32dd90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('permissions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index('ix_unique_permission_name', table_name='permissions')
    op.drop_constraint('permissions_name_key', 'permissions', type_='unique')
    op.create_index('ix_unique_permission_action', 'permissions', ['action'], unique=True)
    op.drop_column('permissions', 'name')
    op.create_unique_constraint('uq_role_permission', 'role_permissions', ['role_id', 'permission_id'])
    op.alter_column('roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('roles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_unique_constraint('uq_user_role', 'user_roles', ['user_id', 'role_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_role', 'user_roles', type_='unique')
    op.alter_column('roles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint('uq_role_permission', 'role_permissions', type_='unique')
    op.add_column('permissions', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index('ix_unique_permission_action', table_name='permissions')
    op.create_unique_constraint('permissions_name_key', 'permissions', ['name'])
    op.create_index('ix_unique_permission_name', 'permissions', ['name'], unique=True)
    op.alter_column('permissions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
