"""add created_at to quiz feedback model

Revision ID: d35f25fb8d23
Revises: 9a229b525159
Create Date: 2024-09-15 17:30:20.823865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd35f25fb8d23'
down_revision: Union[str, None] = '9a229b525159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_feedback', sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True))
    op.alter_column('quiz_feedback', 'quiz_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz_feedback', 'quiz_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('quiz_feedback', 'created_at')
    # ### end Alembic commands ###
