"""quizz models

Revision ID: 1f5e5ebc5881
Revises: 797d63d53a8c
Create Date: 2024-09-13 20:54:31.378344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f5e5ebc5881'
down_revision: Union[str, None] = '797d63d53a8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('attempt_number', sa.INTEGER(), nullable=False),
    sa.Column('score', sa.FLOAT(), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('completed', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.INTEGER(), nullable=False),
    sa.Column('feedback_text', sa.TEXT(), nullable=False),
    sa.Column('min_score', sa.FLOAT(), nullable=False),
    sa.Column('max_score', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.INTEGER(), nullable=False),
    sa.Column('average_score', sa.FLOAT(), nullable=False),
    sa.Column('median_score', sa.FLOAT(), nullable=False),
    sa.Column('standard_deviation', sa.FLOAT(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.INTEGER(), nullable=False),
    sa.Column('browser_security', sa.VARCHAR(length=255), nullable=False),
    sa.Column('shuffle_questions', sa.BOOLEAN(), nullable=False),
    sa.Column('shuffle_answers', sa.BOOLEAN(), nullable=False),
    sa.Column('max_attempts', sa.INTEGER(), nullable=True),
    sa.Column('time_limit', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('slug', sa.VARCHAR(length=255), nullable=False),
    sa.Column('max_scores', sa.INTEGER(), nullable=True),
    sa.Column('max_questions', sa.INTEGER(), nullable=True),
    sa.Column('difficulty', sa.INTEGER(), nullable=False),
    sa.Column('time_limit', sa.INTEGER(), nullable=True),
    sa.Column('published', sa.BOOLEAN(), nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quizzes')
    op.drop_table('quiz_settings')
    op.drop_table('quiz_reports')
    op.drop_table('quiz_feedback')
    op.drop_table('quiz_attempts')
    # ### end Alembic commands ###
