"""add unique constraint

Revision ID: 46640d64f04d
Revises: 7bf5fa37414c
Create Date: 2024-09-07 08:33:36.538950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '46640d64f04d'
down_revision: Union[str, None] = '7bf5fa37414c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_unique_email', 'users', ['email'], unique=True)
    op.create_index('ix_unique_username', 'users', ['username'], unique=True)
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index('ix_unique_username', table_name='users')
    op.drop_index('ix_unique_email', table_name='users')
    # ### end Alembic commands ###
