"""setup user

Revision ID: 673e02ff8751
Revises: 
Create Date: 2025-01-26 13:54:28.827290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '673e02ff8751'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column(
                        'email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('password_hash',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('phone_number',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('email_verified', sa.Boolean(), nullable=False),
                    sa.Column('phone_verified', sa.Boolean(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('is_locked', sa.Boolean(), nullable=False),
                    sa.Column('mfa_secret_key',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
                    sa.Column('last_login', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('phone_number')
                    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user',
                    ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
